name: Better Broadcast
version: 0.2
main: me.bman.betterbcast.main.BetterBcast
description: A more professional looking broadcast
commands:
  bb:
    description: The main command for Better Broadcast